name: Deploy to Cloud Run
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy SERVICE_NAME --image gcr.io/PROJECT_ID/IMAGE_NAME --region us-central1
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}

# need to update my project id and my container image name and the service name
