name: Deploy to Cloud Run

on:
  push:
    branches:
      - master  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup GCP Service Account
      run: echo '${{secrets.GCP_SA_KEY}}' > gcp-sa.json
      shell: bash

    - name: Deploy to Cloud Run
      run: |
        gcloud auth activate-service-account --key-file=gcp-sa.json
        gcloud beta run deploy my-service --image gcr.io/project-id/my-container --platform managed
